/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Preset = IDL.Record({
  'name' : IDL.Text,
  'eqSettings' : IDL.Text,
  'correctionSettings' : IDL.Text,
  'boostLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deletePreset' : IDL.Func([IDL.Text], [], []),
  'getAllPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
  'loadPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
  'savePreset' : IDL.Func([IDL.Text, Preset], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Preset = IDL.Record({
    'name' : IDL.Text,
    'eqSettings' : IDL.Text,
    'correctionSettings' : IDL.Text,
    'boostLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    'deletePreset' : IDL.Func([IDL.Text], [], []),
    'getAllPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
    'loadPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
    'savePreset' : IDL.Func([IDL.Text, Preset], [], []),
  });
};

export const init = ({ IDL }) => { return []; };